@echo off
echo ================================================================================
echo Regenerating LaTeX Figures with Helvetica Font
echo ================================================================================
echo.

cd /d C:\Personal\Coach_WAR

echo [1/2] Generating three-coach trajectory figure...
python analysis\create_trajectory_figure.py --font Helvetica
if %errorlevel% neq 0 (
    echo ERROR: Failed to generate trajectory figure
    exit /b 1
)

echo.
echo [2/2] Generating career distribution figure...
python analysis\create_career_distribution_figure.py --font Helvetica
if %errorlevel% neq 0 (
    echo ERROR: Failed to generate career distribution figure
    exit /b 1
)

echo.
echo ================================================================================
echo SUCCESS! Both LaTeX figures regenerated with Helvetica font
echo ================================================================================
echo.
echo Figures saved to: latex\figures\
echo   - coach_trajectories_oconnell_shula_eberflus.png
echo   - coach_career_distributions.png
echo.
echo Note: Other figures in latex\figures\ were generated by other analysis scripts.
echo To regenerate those with Helvetica, you would need to modify those scripts
echo to accept a --font argument similar to the two above.
echo.

pause
