"""
Quick script to regenerate all LaTeX figures with Helvetica font.
Uses matplotlib rcParams to set font globally before running scripts.
"""

import subprocess
import sys
import os

def setup_font_environment(font='Helvetica'):
    """Set environment variable for matplotlib font configuration."""
    # Create a matplotlib config that will be imported
    config_code = f"""
import matplotlib.pyplot as plt
import matplotlib as mpl

# Configure fonts
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.sans-serif'] = ['{font}', 'DejaVu Sans', 'Arial']
plt.rcParams['font.size'] = 10
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['axes.labelsize'] = 12
plt.rcParams['figure.dpi'] = 300
plt.rcParams['savefig.dpi'] = 300
print(f"Configured matplotlib with {font} font")
"""
    return config_code

def run_with_font_config(script_path, font='Helvetica'):
    """Run a script with font configuration prepended."""
    config = setup_font_environment(font)

    # Run with custom matplotlib setup
    cmd = [
        sys.executable, '-c',
        config + f"\nimport runpy; runpy.run_path('{script_path}')"
    ]

    print(f"\nRunning: {os.path.basename(script_path)}")
    try:
        result = subprocess.run(cmd, check=True, capture_output=True, text=True, cwd=os.getcwd())
        print(result.stdout)
        if result.stderr and 'warning' not in result.stderr.lower():
            print("STDERR:", result.stderr)
        return True
    except subprocess.CalledProcessError as e:
        print(f"ERROR: {e}")
        print(e.stdout)
        print(e.stderr)
        return False

def main():
    font = 'Helvetica'

    print(f"{'='*80}")
    print(f"REGENERATING LATEX FIGURES WITH {font.upper()} FONT")
    print(f"{'='*80}\n")

    # Scripts that generate the latex figures
    scripts = [
        'analysis/create_trajectory_figure.py',
        'analysis/create_career_distribution_figure.py',
    ]

    # Also copy figures from outputs/png to latex/figures
    copy_commands = [
        ('analysis/outputs/png/coach_2024_matrix.png', 'latex/figures/'),
        ('analysis/outputs/png/coach_2024_trajectories.png', 'latex/figures/'),
        ('analysis/outputs/png/coach_2024_single_year_bar.png', 'latex/figures/'),
        ('analysis/outputs/png/coach_background_from_history_15seasons.png', 'latex/figures/'),
        ('analysis/outputs/png/coaching_war_persistence_scatter.png', 'latex/figures/'),
        ('analysis/outputs/png/coaching_regression_to_mean_survivorship_adjusted.png', 'latex/figures/'),
        ('analysis/outputs/png/coaching_survivorship_bias_magnitude.png', 'latex/figures/'),
        ('analysis/outputs/png/win_pct_persistence_scatter.png', 'latex/figures/'),
        ('analysis/outputs/png/coaching_war_persistence_by_background.png', 'latex/figures/'),
        ('analysis/outputs/png/coaching_war_multiyear_persistence_scatter.png', 'latex/figures/'),
    ]

    success_count = 0
    for script in scripts:
        if run_with_font_config(script, font):
            success_count += 1

    print(f"\n{'='*80}")
    print(f"Generated {success_count}/{len(scripts)} custom figures successfully")
    print(f"{'='*80}\n")

    print("Note: Other figures in latex/figures/ were generated by other scripts.")
    print("Run the individual analysis scripts with --font Helvetica if they support it,")
    print("or regenerate from their source scripts manually.")

if __name__ == "__main__":
    main()
